# Generated by Django 4.0.5 on 2022-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coindata',
            old_name='datetime',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='coindata',
            name='price',
            field=models.CharField(max_length=40),
        ),
    ]
