# Generated by Django 4.0.5 on 2022-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_rename_datetime_coindata_time_alter_coindata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindata',
            name='time',
            field=models.CharField(max_length=40),
        ),
    ]
