# Generated by Django 4.0.5 on 2022-07-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0003_alter_coindata_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coindata',
            old_name='time',
            new_name='newtime',
        ),
    ]
